name = "AdaptiveParticleMCMC"
uuid = "80dd4f21-a330-47dc-9fe5-4758e06b94f1"
version = "0.1.2"
authors = ["Matti Vihola <mvihola@iki.fi>"]

[deps]
AdaptiveMCMC = "717c3277-546c-407d-8270-09a39a0919a0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
SequentialMonteCarlo = "8c675823-c5d5-50f8-acb2-29aff48dfc1d"

[extensions]
AdaptiveParticleMCMCSequentialMonteCarloExt = "SequentialMonteCarlo"

[compat]
AdaptiveMCMC = ">= 0.1.1"
julia = "1.9"
